### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by jholleran**
Bump revision to release the OIDC configuration bug fix.

https://github.com/solid/oidc-op/pull/24/files

### CODE REVIEW

**Comment by michielbdejong** [comment]
Thanks, I'm doing this with `npm version minor` in the master branch.

**Comment by jholleran** [comment]
Thanks Michiel. Can you also update these dependencies in NSS?

**Comment by michielbdejong** [comment]
Yes, done in NSS v5.5.1, see https://gitter.im/solid/node-solid-server

**Comment by jholleran** [comment]
Great. Thanks a million!

**Pull request closed without merging**
