### PR TITLE
OpenLink changes relating to Solid logout and switching accounts

### PR DESCRIPTION
**Pull request by cblakeley**
Related issues:
https://github.com/solid/oidc-auth-manager/issues/20
https://github.com/solid/node-solid-server/issues/675

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Thanks @cblakeley!

**Comment by dmitrizagidulin** [comment]
(This PR is superceded by https://github.com/solid/oidc-op/pull/7). Leaving this open for the moment as a reminder, will close later.

**Comment by cblakeley** [comment]
@dmitrizagidulin As this PR was superceded by solid/oidc-op#7, can you now close it? Thanks.

**Comment by dmitrizagidulin** [comment]
@cblakeley no prob. closing.

**Pull request closed without merging**
